### ISSUE TITLE
Google OAuth login exception

### ISSUE THREAD

**Issue by Aeolun** [thephpleague/oauth2-client#550]
If you try to login with Google, and try to retrieve google plus details while the API is not enabled, the system tries to create an exception, but fails because the expected string is really an array.

I guess this issue might be limited to PHP7?

```
Fatal error: Uncaught Error: Wrong parameters for League\OAuth2\Client\Provider\Exception\IdentityProviderException([string $message [, long $code [, Throwable $previous = NULL]]]) in /vagrant/vendor/league/oauth2-client/src/Provider/Exception/IdentityProviderException.php:36 
Stack trace: 
#0 /vagrant/vendor/league/oauth2-client/src/Provider/Exception/IdentityProviderException.php(36): Exception->__construct(Array, 0) 
#1 /vagrant/vendor/league/oauth2-client/src/Provider/GenericProvider.php(216): League\OAuth2\Client\Provider\Exception\IdentityProviderException->__construct(Array, 0, Array) 
#2 /vagrant/vendor/league/oauth2-client/src/Provider/AbstractProvider.php(644): League\OAuth2\Client\Provider\GenericProvider->checkResponse(Object(GuzzleHttp\Psr7\Response), Array) 
#3 /vagrant/vendor/league/oauth2-client/src/Provider/AbstractProvider.php(793): League\OAuth2\Client\Provider\AbstractProvider->getResponse(Object(GuzzleHttp\Psr7\Request)) 
#4 /vagrant/vendor/league/oauth2-client/src/Provider/AbstractProvider.php(776): League in /vagrant/vendor/league/oauth2-client/src/Provider/Exception/IdentityProviderException.php on line 36
```

**Comment by shadowhand** [comment]
Looks like you are using GenericProvider to connect to Google. Any particular reason you aren't using `oauth2-google`?
