### ISSUE TITLE
Error in refresh token obtained

### ISSUE THREAD

**Issue by laurelBE** [thephpleague/oauth2-client#701]
I am using gmail_xoauth.php for oauth with sending email, when i run it on browser it gives error as below

```
PHP Fatal error:  Uncaught League\OAuth2\Client\Provider\Exception\IdentityProviderException: invalid_grant in C:\inetpub\wwwroot\bephpforTteam\GoogleOauthLogin\PHPMailer5\vendor\league\oauth2-google\src\Provider\Google.php:120
Stack trace:
#0 C:\inetpub\wwwroot\bephpforTteam\GoogleOauthLogin\PHPMailer5\vendor\league\oauth2-client\src\Provider\AbstractProvider.php(613): League\OAuth2\Client\Provider\Google->checkResponse(Object(GuzzleHttp\Psr7\Response), Array)
#1 C:\inetpub\wwwroot\bephpforTteam\GoogleOauthLogin\PHPMailer5\vendor\league\oauth2-client\src\Provider\AbstractProvider.php(528): League\OAuth2\Client\Provider\AbstractProvider->getParsedResponse(Object(GuzzleHttp\Psr7\Request))
#2 C:\inetpub\wwwroot\bephpforTteam\GoogleOauthLogin\PHPMailer5\class.phpmaileroauthgoogle.php(69): League\OAuth2\Client\Provider\AbstractProvider->getAccessToken(Object(League\OAuth2\Client\Grant\RefreshToken), Array)
#3 C:\inetpub\wwwroot\bephpforTteam\GoogleOauthLogin\PHPMailer5\class.phpmaileroauthgoogle.php(74): PHPMailerOAuthGoogle->getT in C:\inetpub\wwwroot\bephpforTteam\GoogleOauthLogin\PHPMailer5\vendor\league\oauth2-google\src\Provider\Google.php on line 120
```
I have install composer require league/oauth2-google from terminal

**Comment by ramsey** [comment]
This is an error that the provider is returning, please post a question at [league/oauth2-google](https://github.com/thephpleague/oauth2-google), if this is still a problem.
